# Based on:
# https://medium.com/appditto/automate-your-flutter-workflow-using-gitlab-ci-cd-and-fastlane-5872e758165a

# Update fastlane automatically
update_fastlane

default_platform(:android)

platform :android do
  desc "Build android aab and apk"
  lane :build_android do |options|
    # Run tests (deactivated, already done in gitlab-ci)
    # sh "./flutter_test.sh"
    # Clean before building
    sh "./flutter_build.sh --clean"
    # Build AAB
    sh "./flutter_build.sh"
    # Build APK
    sh "./flutter_build.sh --apk"
  end

  desc "Deploy (Upload to play store)"
  lane :deploy_android do |options|
    upload_to_play_store(
      track: options[:production] ? 'production' : options[:internal] ? 'internal' : options[:alpha] ? 'alpha' : 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end